- src/app/directives/header/userMenu/settings/userMenu.settings.html
- src/assets/styles/main.css
- src/scss/opintoni/_user-menu.scss
One !important so that we don't have to rewrite all of the dropdown-menu.
> OO-431 Whole user settings menu line as a link

- src/app/directives/header/userMenu/settings/userMenu.settings.directive.js
- src/app/directives/header/userMenu/settings/userMenu.settings.html
- src/app/directives/usefulLinks/usefulLinks.html
- src/app/directives/visibility/visibility.directive.js
- src/app/partials/layout.html
- src/app/resources/portfolio.resource.js
- src/app/services/portfolio.service.js
- src/i18n/opintoni-en.json
- src/i18n/opintoni-fi.json
- src/i18n/opintoni-sv.json
- test/spec/unit/directives/visibility/visibilityDirectiveSpec.js
Hybrid users have links to both of their portfolios both in my studies and in my teachings.
> OO-502 hybrid user portfoliolinks

- src/app/directives/header/userMenu/settings/userMenu.settings.avatar.html
- src/app/directives/uploadImage/uploadImage.directive.js
Second take from two weeks ago. Most of the old comments included.
(The &nbsp; is still there as a minor style issue, which would need much more rewriting.)
> OO-463 fixed mobile image cropper for the avatar image

- portfolio/src/app/directives/freeTextContent/freeTextContent.directive.js
> Direct editing of new free text content

- portfolio/src/app/directives/credits/credits.directive.js
- portfolio/src/app/directives/credits/credits.html
(as there won't be any coming from the service)
> Show default 43 credits in demo

- main/src/app/constants/externalLinks.js
- main/src/app/directives/header/pageNavigation/pageNavigation.directive.js
Toteutettu tämän piirissä mekanismi, jolla erotella navigaatiot. Varsinaiset navigaatio muutokset sitten omien tikettiensä puitteissa.
> Opetukseni- ja Opintoni-sivulle tarvitaan omat navigaatiot

- npm-shrinkwrap.json
- package.json
- portfolio/src/app/directives/degrees/degrees.directive.js
- portfolio/src/app/directives/languageProficiencies/languageProficiencies.directive.js
- portfolio/src/app/directives/workExperience/workExperience.directive.js
- portfolio/test/spec/unit/directives/languageProficienciesDirectiveSpec.js
Added a missing dependency to jasmine-core.
Fixed some js warnings.
> OO-1004 portfolio data not updated on screen

- common/src/app/directives/favorites/favorites.addNew.directive.js
- common/src/app/directives/favorites/favorites.addNew.popover.html
- common/src/app/directives/favorites/favorites.addNew.search.html
- common/src/app/directives/favorites/link/favorites.addNew.link.directive.js
- main/src/app/directives/favorites/favorites.html
- main/src/scss/opintoni/_edit-link.scss
- main/src/scss/opintoni/_favorites.scss
- main/src/scss/opintoni/_opintoni.scss
- main/src/scss/opintoni/_popover.scss
- main/src/scss/opintoni/_week-feed.scss
- portfolio/src/app/directives/favorites/favorites.directive.js
- portfolio/src/app/directives/favorites/favorites.html
Suosikit-linkkiä luodessa (portfoliossa) syöttökentän jälkeen on tallennusväkänen joka toimii vastaavasti kuin enterin painaminen.
Samalla laitettu lisää suosikki -nappi visuaalisesti samanlaiseksi kuin muut klikattavat asiat, eli sininen ja hover-efekti tummemman siniseksi.
> OO-1110 save-button for favorite link 

- portfolio/src/app/directives/workExperience/editWorkExperience.directive.js
- portfolio/src/app/directives/workExperience/editWorkExperience.html
- portfolio/src/app/resources/workExperience.resource.js
- portfolio/src/app/services/workExperience.service.js
- portfolio/src/scss/portfolio/_work-experience.scss
Työkokemuksen sorttaus, fronttipuoli. Piti sahata ratkaisujen välillä kun drag and drop aiheutti valintaa väärissä elementeissä.
> Oo 1112 drag ordering for work experience

- common/src/scss/styleguide/_styleguide.scss
- main/src/app/directives/header/pageNavigation/pageNavigation.html
- main/src/scss/opintoni/_page-navigation.scss
Reverts UH-StudentServices/mystudies-myteaching-frontend#282
> Revert "OO-1119 Fix tools menu CSS bugs"

- .eslintrc.json
- bower.json
- common/src/app/vendor/ng-embed.js
- package-lock.json
- portfolio/src/app/app.js
- portfolio/src/app/controllers/ckeditor.js
- portfolio/src/app/directives/browseFiles/browseFiles.directive.js
- portfolio/src/app/directives/browseFiles/browseFiles.html
- portfolio/src/app/directives/freeTextContent/freeTextContent.html
- portfolio/src/app/partials/_files.html
- portfolio/src/app/resources/browseFiles.resource.js
- portfolio/src/app/services/browseFiles.service.js
- portfolio/src/i18n/portfolio-en.json
- portfolio/src/i18n/portfolio-fi.json
- portfolio/src/i18n/portfolio-sv.json
- portfolio/src/index.html
- portfolio/src/scss/portfolio/_files.scss
- portfolio/src/scss/portfolio/_portfolio.scss
Lisätty CKEditor vapaan tekstikentän muokkaamiseen. Editorilla voi lisätä tekstiin linkkejä ja ladata tiedostoja palvelimelle, sekä listata käyttäjän lataamat tiedostot.
> OO-1104 Portfolio file upload

- portfolio/src/app/analytics/analytics.js
- portfolio/src/app/app.js
- portfolio/src/app/directives/attainments/attainments.directive.js
- portfolio/src/app/directives/chooseBackground/chooseBackground.directive.js
- portfolio/src/app/directives/contactInformation/contactInformation.directive.js
- portfolio/src/app/directives/degrees/degrees.directive.js
- portfolio/src/app/directives/editableHeading/editableHeading.directive.js
- portfolio/src/app/directives/favorites/favorites.directive.js
- portfolio/src/app/directives/freeTextContent/addFreeTextContent.directive.js
- portfolio/src/app/directives/freeTextContent/freeTextContent.directive.js
- portfolio/src/app/directives/intro/intro.directive.js
- portfolio/src/app/directives/languageProficiencies/languageProficiencies.directive.js
- portfolio/src/app/directives/samples/samples.directive.js
- portfolio/src/app/directives/studies/keywords.directive.js
- portfolio/src/app/directives/studies/studies.directive.js
- portfolio/src/app/directives/visibility/visibility.directive.js
- portfolio/src/app/directives/workExperience/workExperience.directive.js
- portfolio/test/spec/unit/directives/languageProficienciesDirectiveSpec.js
- Added event tracking to multiple user actions.
- Added page tracking to app init.
> OO-551 Opiskelijaportfolio googleanalyticsiin

- main/src/scss/opintoni/_variables.scss
- portfolio/src/app/directives/intro/intro.html
- portfolio/src/scss/portfolio/_intro.scss
- portfolio/src/scss/portfolio/_page-banner.scss
Lisätty opacity 0.4 musta overlay banneriin, ja muutettu edit-ikoni valkoiseksi
> OO-1158 - Bannerikuvien varjostus

- common/src/app/directives/currentLang/currentLang.directive.js
- main/src/app/app.js
- main/src/index.html
- package-lock.json
- portfolio/src/app/app.js
- portfolio/src/index.html
- Added the currentLang directive and used in the html element of the Main and Portfolio index.html files.
> OO-835 Laita kieli html-tagiin

- portfolio/src/app/directives/freeTextContent/freeTextContent.html
- portfolio/src/app/directives/intro/intro.html
- limited visibility of two buttons to the user himself:
- background image change button
- free text field delete button
> OO-1181 portfolion ikonien näkyvyys julkaistuna

- common/test/e2e/util/index.js
- main/src/i18n/opintoni-en.json
- main/src/i18n/opintoni-fi.json
- main/src/i18n/opintoni-sv.json
- portfolio/src/i18n/portfolio-en.json
- portfolio/src/i18n/portfolio-fi.json
- portfolio/src/i18n/portfolio-sv.json
- Changed "profile" back to "portfolio" in the UI texts. Until the new term is officially launched.
> OO-1211 Muutetaan vielä käyttöliittymässä Profiili -> Portfolio

- main/src/scss/opintoni/_common_elements.scss
- main/src/scss/opintoni/_component-header.scss
- main/src/scss/opintoni/_help-icon.scss
- profile/src/app/directives/attainments/attainments.html
- profile/src/app/directives/contactInformation/contactInformation.html
- profile/src/app/directives/degrees/degrees.html
- profile/src/app/directives/editableHeading/editableHeading.directive.js
- profile/src/app/directives/editableHeading/editableHeading.html
- profile/src/app/directives/freeTextContent/addFreeTextContent.html
- profile/src/app/directives/freeTextContent/freeTextContent.html
- profile/src/app/directives/languageProficiencies/languageProficiencies.html
- profile/src/app/directives/samples/samples.html
- profile/src/app/directives/studies/studies.html
- profile/src/app/directives/visibility/visibilityToggle.html
- profile/src/app/directives/workExperience/workExperience.html
- profile/src/scss/profile/_contact-information.scss
- profile/src/scss/profile/_free-text-content.scss
- profile/src/scss/profile/_profile-general.scss
Tehdään portfolion otsikkorivi niin että otsikko+helppinappi on oma flexboxinsa ja toimintonapit oma flexboxi ja koko otsikkorivi on flexboxi joka asemoi otsikon vasemmalle ja toimintonapit oikealle.
Mobiilinäkymässä myös otsikon muokkaus käyttää pienempää otsikkofonttia.
> OO-1294 mobile align fixes for portfolio actions 

- profile/src/assets/icons/drag-icon.svg
- profile/src/scss/profile/_profile-general.scss
Until we can use drag icon from HY fonts
> Changed drag icon to separate svg image

- profile/src/app/app.js
- An empty white page was shown in Profile root when there was a profile for the user but in a different language thant the UI language.
> OO-1416 Profiilissa rikkonaisia osia

- main/src/app/app.js
- Make a page refresh to /opintoni in order to trigger the Nginx redirect to the new Opintoni.
> https://jira.it.helsinki.fi/browse/OO-1478 /opintoni-ohjaus fronttiin
